var num = 102;
$(document).ready(function(){ 
	$("#herolist").html(getHeroList());
	$("#herolist").listview( "refresh" );
});

function getHeroList(){
	var str = '';
	var src, name;
	for(var i=0; i<num; i++){
		name = heroes[i];
		src = '"heroes/hero ('+i+').png"';
		str += '<li><a href="#"><img class="hero" src='+src+'/><div class="hero">'+name+'</div></a></li>';
	}
	return str;
}


var heroes = [
    "Abaddon",
    "Alchemist",
    "Ancient Apparition",
    "Anti-Mage",
    "Axe",
    "Bane",
    "Batrider",
    "Beastmaster",
    "Bloodseeker",
    "Bounty Hunter",
    "Brewmaster",
    "Bristleback",
    "Centaur Warrunner",
    "Chaos Knight",
    "Chen",
    "Clinkz",
    "Clockwerk",
    "Crystal Maiden",
    "Dark Seer",
    "Dazzle",
    "Death Prophet",
    "Disruptor",
    "DOOM",
    "Dragon Knight",
    "Drow",
    "Earthshaker",
    "Elder Titan",
    "Ember Spirit",
    "Enchantress",
    "Enigma",
    "Faceless Void",
    "Gyrocopter",
    "Huskar",
    "Invoker",
    "Io",
    "Jakiro",
    "Juggernaught",
    "Keeper of the Light",
    "Kunkka",
    "Leshrac",
    "Lich",
    "Lifestealer",
    "Lina",
    "Lion",
    "Lone Druid",
    "Luna",
    "Lycanthrope",
    "Magnus",
    "Medusa",
    "Meepo",
    "Mirana",
    "Morphling",
    "Naga Siren",
    "Nature's Prophet",
    "Necrophos",
    "Nightstalker",
    "Nyx Assassin",
    "Outworld Devourer",
    "Ogre Magi",
    "Omniknight",
    "Phantom Assassin",
    "Phantom Lancer",
    "Puck",
    "Pudge",
    "Pugna",
    "Queen of Pain",
    "Razor",
    "Riki",
    "Rubick",
    "Sand King",
    "Shadow Demon",
    "Shadow Fiend",
    "Shadow Shaman",
    "Silencer",
    "Skywrath Mage",
    "Slardar",
    "Slark",
    "Sniper",
    "Spectre",
    "Spirit Breaker",
    "Storm Spirit",
    "Sven",
    "Templar Assassin",
    "Tidehunter",
    "Timbersaw",
    "Tinker",
    "Tiny",
    "Treant Protector",
    "Troll Warlord",
    "Tusk",
    "Undying",
    "Ursa",
    "Vengeful Spirit",
    "Venomancer",
    "Viper",
    "Visage",
    "Warlock",
    "Weaver",
    "Windranger",
    "Witch Doctor",
    "Wraith King",
    "Zeus"
	];